using System.Text;

namespace Mirage.Scripting;

/// <summary>
/// The engine's own types, written out as Compass a checker can read.
///
/// <para>🔴 <b>A world's rules name types that exist only inside a running server.</b> The catalog is
/// built while a world loads and its members are delegates in that process, so `cm check` and the VS
/// Code language server have never heard of <c>Builder</c> or <c>Player</c> and report every
/// declaring line as an unknown type. The author is then told their own correct code is wrong, on
/// every line that matters, which trains them to ignore the tooling.</para>
///
/// <para>So the engine writes the catalog down: an abstract model per registered type, every member
/// declared and left open at a semicolon. Nothing runs it — it exists to be read by a checker that
/// cannot see inside the server.</para>
///
/// <para>⚠ <b>It must not live under <c>scripts/</c>.</b> The engine compiles every <c>.cm</c> there,
/// and a second declaration of <c>Builder</c> would collide with the catalog's own.</para>
/// </summary>
public static class ScriptStubs
{
    /// <summary>The folder inside a world that holds the written-down catalog.</summary>
    public const string Folder = ".mirage";

    /// <summary>The file inside it.</summary>
    public const string StubFile = "engine.cm";

    /// <summary>The project file at the world's root, which ties the two folders together.</summary>
    public const string ProjectFile = "world.cmp";

    private const string Warning =
        "# GENERATED by the server when it loads this world. Do not edit.\n"
        + "#\n"
        + "# These are the types the engine hands a script: what a Builder offers, what a Player\n"
        + "# offers, and so on. They are declared and left open because nothing here runs — the real\n"
        + "# members live in the server, and this exists so `cm check` and the VS Code extension can\n"
        + "# see what your rules are talking about.\n"
        + "#\n"
        + "# What each member does is written above it, so hovering one in the editor answers the\n"
        + "# question without leaving the file.\n";

    /// <summary>The stub source for a catalog.</summary>
    public static string Stub(ScriptCatalog catalog)
    {
        ArgumentNullException.ThrowIfNull(catalog);

        var text = new StringBuilder(Warning);

        foreach (ScriptTypeInfo type in catalog.Types)
        {
            text.Append('\n').Append(Note(type.Note, indent: 0));

            // Shared where the catalog says shared, so a script reaches it by its own name; abstract
            // either way, because only an abstract model may carry a function with no body.
            text.Append(type.Shared ? "shared abstract model " : "abstract model ")
                .Append(type.Name).Append('\n');

            foreach (ScriptMemberInfo member in type.Members)
            {
                text.Append(Note(member.Note, indent: 4))
                    .Append("    ").Append(Member(member)).Append('\n');
            }

            text.Append("end model\n");
        }

        return text.ToString();
    }

    /// <summary>One member: a field for a value, an open function for a call.</summary>
    private static string Member(ScriptMemberInfo member)
    {
        if (member.IsValue)
        {
            // Read without parentheses, so it has to be a field rather than a function.
            return $"public {member.Yields} {member.Name};";
        }

        string takes = string.Join(", ", member.Takes);
        string yields = member.Yields.IsNothing ? string.Empty : member.Yields + " ";

        return $"public abstract {yields}function {member.Name}({takes});";
    }

    /// <summary>
    /// What a model or a member is, as the documentation comment an editor shows on hover.
    ///
    /// <para>A Compass documentation comment is a block opening with <c>@summary:</c> — a block that
    /// does not is ordinary prose, which is how a remark above a declaration stays a remark. The
    /// language server finds it by the line it sits above, so the member follows immediately.</para>
    ///
    /// <para>Empty for anything nobody has written a note for, rather than an empty comment.</para>
    /// </summary>
    private static string Note(string note, int indent)
    {
        if (note.Length == 0) return string.Empty;

        string pad = new(' ', indent);

        // A model's comment opens the block it belongs to, so it takes the blank line the loop
        // already wrote. A member's has to make its own, or every member runs into the one above it.
        var text = new StringBuilder(indent == 0 ? "##\n" : "\n" + pad + "##\n");

        foreach (string line in Wrapped(note, 92))
        {
            text.Append(pad).Append("    ").Append(line).Append('\n');
        }

        return text.Append(pad).Append("##\n").ToString();
    }

    /// <summary>A note as lines that fit, the first one carrying the label.</summary>
    private static IEnumerable<string> Wrapped(string note, int width)
    {
        var line = new StringBuilder("@summary:");

        foreach (string word in note.Split(' ', StringSplitOptions.RemoveEmptyEntries))
        {
            if (line.Length > 0 && line.Length + 1 + word.Length > width)
            {
                yield return line.ToString();
                line.Clear();
            }

            if (line.Length > 0) line.Append(' ');

            line.Append(word);
        }

        if (line.Length > 0) yield return line.ToString();
    }

    /// <summary>
    /// The project file that makes a checker read the whole module at once.
    ///
    /// <para>A <c>source</c> naming a folder takes the <c>.cm</c> files directly inside it and does
    /// not descend, so every folder under <c>scripts/</c> is named in turn. Without this, checking one
    /// file cannot see the models in its siblings.</para>
    /// </summary>
    /// <param name="scriptFolders">Every folder holding scripts, relative to the world, forward-slashed.</param>
    public static string Project(IEnumerable<string> scriptFolders)
    {
        ArgumentNullException.ThrowIfNull(scriptFolders);

        var text = new StringBuilder(
            "# GENERATED by the server when it loads this world. Do not edit.\n"
            + "#\n"
            + "# What a checker builds: the engine's types, then this world's own rules. VS Code finds\n"
            + "# this by asking `cm project` which project builds the file you have open.\n"
            + "\n"
            + "project World\n"
            + "    source " + Folder + "\n");

        foreach (string folder in scriptFolders)
        {
            text.Append("    source ").Append(folder).Append('\n');
        }

        return text.Append("end project\n").ToString();
    }

    /// <summary>
    /// Writes both files under a world, and answers whether anything changed.
    ///
    /// <para>⚠ Only when the content differs. A world folder is somebody's working directory, and
    /// rewriting a file it already holds churns its timestamp and wakes every watcher looking at it.</para>
    /// </summary>
    /// <exception cref="IOException">The world cannot be written to. The caller decides what that
    /// means; a read-only world is a world that still runs.</exception>
    public static bool Write(string worldDir, ScriptCatalog catalog, IEnumerable<string> scriptFolders)
    {
        ArgumentNullException.ThrowIfNull(worldDir);

        string folder = Path.Combine(worldDir, Folder);
        Directory.CreateDirectory(folder);

        return Put(Path.Combine(folder, StubFile), Stub(catalog))
             | Put(Path.Combine(worldDir, ProjectFile), Project(scriptFolders));
    }

    private static bool Put(string path, string content)
    {
        if (File.Exists(path) && File.ReadAllText(path) == content) return false;

        File.WriteAllText(path, content);
        return true;
    }
}
